# Generated by Django 5.0.1 on 2024-03-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Обо мне', max_length=126)),
                ('photo', models.ImageField(upload_to='images')),
                ('text', models.TextField()),
            ],
        ),
    ]
