# Generated by Django 5.0.1 on 2024-02-21 13:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=126, null=True, verbose_name='name')),
                ('date_wrote', models.DateField(default=datetime.datetime.now, verbose_name='date_wrote')),
                ('date_of_change', models.DateField(blank=True, null=True, verbose_name='date_of_change')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.IntegerField(blank=True, null=True, verbose_name='paragraph')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('header', models.CharField(blank=True, max_length=126, null=True, verbose_name='header')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.article')),
            ],
        ),
    ]
